export const students = [
  { id:'aarav', name:'Aarav Kumar', role:'Data Analyst Student', city:'Chennai', skills:['Python','SQL','Excel','Power BI'], rating:4.9, completed:12, earned:14800, availability:'Available this week', verified:['Sales Dashboard','Customer Churn Analysis','Inventory Analysis'] },
  { id:'meera', name:'Meera Iyer', role:'Product Design Student', city:'Bangalore', skills:['Figma','Canva','UI Design','Branding'], rating:4.8, completed:10, earned:12600, availability:'Available this week', verified:['Cafe Brand Kit','Event Invitations','Mobile App UI'] },
  { id:'rohan', name:'Rohan Patel', role:'Web Development Student', city:'Mumbai', skills:['React','CSS','JavaScript','WordPress'], rating:4.8, completed:15, earned:22100, availability:'Available in 2 days', verified:['Restaurant Website','Product Catalogue','NGO Landing Page'] },
  { id:'kavya', name:'Kavya Nair', role:'Marketing Student', city:'Kochi', skills:['SEO','Canva','Instagram','Content'], rating:4.7, completed:9, earned:9400, availability:'Available this week', verified:['Bakery Campaign','Local Store Socials','SEO Audit'] },
  { id:'vikram', name:'Vikram Shah', role:'Data Science Student', city:'Hyderabad', skills:['Python','Excel','Tableau','Statistics'], rating:4.9, completed:18, earned:27500, availability:'Available tomorrow', verified:['Survey Analysis','Sales Forecast','Market Research'] },
  { id:'nisha', name:'Nisha Singh', role:'Document Specialist', city:'Delhi', skills:['MS Word','Excel','Canva','Typing'], rating:4.8, completed:22, earned:18200, availability:'Available this week', verified:['Resume Redesign','PDF Conversion','Expense Tracker'] },
  { id:'sanjay', name:'Sanjay Rao', role:'Frontend Student', city:'Coimbatore', skills:['React','Tailwind','HTML','Firebase'], rating:4.7, completed:11, earned:16700, availability:'Available in 3 days', verified:['Portfolio Site','Local Business Site','Dashboard UI'] },
  { id:'priya', name:'Priya Menon', role:'Business Analytics Student', city:'Bangalore', skills:['Excel','Power BI','SQL','Google Sheets'], rating:4.8, completed:14, earned:19300, availability:'Available this week', verified:['Retail Dashboard','Inventory Report','Cafe Metrics'] },
  { id:'aditya', name:'Aditya Verma', role:'Technology Support Student', city:'Delhi', skills:['Google Workspace','WordPress','Excel','Tech Support'], rating:4.6, completed:8, earned:8900, availability:'Available tomorrow', verified:['Email Setup','Website Update','Sheets Automation'] },
  { id:'farah', name:'Farah Ali', role:'Visual Design Student', city:'Chennai', skills:['Canva','Adobe Express','Illustration','Social Media'], rating:4.9, completed:16, earned:20800, availability:'Available this week', verified:['Festival Posters','Menu Design','Social Templates'] }
];

export const tasks = [
  {id:'sales-dashboard',title:'Build a Sales Dashboard',business:'FreshBite Bakery',category:'Data & Analytics',budget:1200,difficulty:'Intermediate',skills:['Excel','Power BI'],deadline:'2 days',description:"We have six months of sales data but don't know which products generate the most revenue."},
  {id:'restaurant-site',title:'Create a Restaurant Website',business:'Spice Route Kitchen',category:'Web Development',budget:2500,difficulty:'Intermediate',skills:['React','CSS'],deadline:'4 days',description:'Create a welcoming one-page menu and reservation website for a local restaurant.'},
  {id:'customer-data',title:'Clean & Analyze Customer Data',business:'Namma Retail',category:'Data & Analytics',budget:900,difficulty:'Beginner',skills:['Python','Excel'],deadline:'1 day',description:'Organise customer feedback and identify recurring themes.'},
  {id:'resume',title:'Redesign My Resume',business:'Ananya, Chennai',category:'Documents',budget:450,difficulty:'Beginner',skills:['MS Word','Canva'],deadline:'2 days',description:'Convert my existing resume into a polished professional layout.'},
  {id:'catalogue',title:'Digital Product Catalogue',business:'Kaveri Crafts',category:'Design',budget:1400,difficulty:'Intermediate',skills:['Canva','Branding'],deadline:'3 days',description:'Create a shareable product catalogue for handmade gifts.'},
  {id:'campaign',title:'Instagram Launch Campaign',business:'Bloom Wellness',category:'Digital Marketing',budget:1800,difficulty:'Intermediate',skills:['Canva','Instagram','Content'],deadline:'5 days',description:'Plan a week of launch posts for a wellness studio.'},
  {id:'inventory',title:'Inventory Analysis',business:'Metro Mart',category:'Data & Analytics',budget:1500,difficulty:'Intermediate',skills:['Excel','SQL'],deadline:'3 days',description:'Find slow-moving items and create a simple inventory report.'},
  {id:'wordpress',title:'Update Local Store Website',business:'Vasanth Stores',category:'Web Development',budget:700,difficulty:'Beginner',skills:['WordPress','CSS'],deadline:'1 day',description:'Refresh business hours, product images and contact information.'},
  {id:'survey',title:'Customer Survey Insights',business:'Chai Junction',category:'Data & Analytics',budget:1000,difficulty:'Beginner',skills:['Excel','Statistics'],deadline:'2 days',description:'Summarise responses from a customer satisfaction survey.'},
  {id:'invitation',title:'Housewarming Invitation Design',business:'Sowmya, Bangalore',category:'Design',budget:350,difficulty:'Beginner',skills:['Canva','Illustration'],deadline:'2 days',description:'Design a modern digital invitation in Tamil and English.'},
  {id:'sheets',title:'Google Sheets Expense Tracker',business:'Rahul, Mumbai',category:'Documents',budget:550,difficulty:'Beginner',skills:['Excel','Google Sheets'],deadline:'1 day',description:'Build an easy monthly tracker with categories and charts.'},
  {id:'seo',title:'Basic SEO Audit',business:'Mango Tree Homestay',category:'Digital Marketing',budget:1100,difficulty:'Intermediate',skills:['SEO','Content'],deadline:'3 days',description:'Identify quick improvements for our website visibility.'},
  {id:'pdf',title:'Convert Scanned Forms to Excel',business:'Sri Lakshmi Traders',category:'Documents',budget:650,difficulty:'Beginner',skills:['Excel','Typing'],deadline:'2 days',description:'Convert 70 handwritten stock forms into a clean spreadsheet.'},
  {id:'tech-help',title:'Set Up Google Workspace',business:'Nila Consulting',category:'Technology Help',budget:800,difficulty:'Beginner',skills:['Google Workspace','Tech Support'],deadline:'2 days',description:'Set up email, shared folders and a basic calendar workflow.'},
  {id:'portfolio',title:'Personal Portfolio Website',business:'Dinesh, Hyderabad',category:'Web Development',budget:2000,difficulty:'Intermediate',skills:['React','Tailwind'],deadline:'5 days',description:'Build a responsive portfolio that showcases photography work.'}
];

export const businesses = [{id:'freshbite',name:'FreshBite Bakery',city:'Chennai'},{id:'spice-route',name:'Spice Route Kitchen',city:'Bangalore'},{id:'namma-retail',name:'Namma Retail',city:'Coimbatore'},{id:'bloom',name:'Bloom Wellness',city:'Hyderabad'},{id:'kaveri',name:'Kaveri Crafts',city:'Mumbai'}];
